# Generated by Django 3.1.6 on 2021-10-26 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absent_date', models.DateField()),
                ('absent_type', models.CharField(blank=True, choices=[('n', 'Normal'), ('v', 'Virtual'), ('e', 'Exam')], default='N', max_length=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendant.student')),
            ],
        ),
    ]
