# Generated by Django 3.1.6 on 2021-11-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendant', '0003_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
        migrations.AddField(
            model_name='student',
            name='student_level',
            field=models.CharField(blank=True, choices=[('10', 'دهم'), ('11', 'یازدهم'), ('12', 'دوازدهم')], default='10', max_length=2),
        ),
    ]
