# Generated by Django 3.1.6 on 2021-12-02 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendant', '0004_auto_20211202_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='school_id',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_classroom',
            new_name='classroom',
        ),
    ]
