# Generated by Django 3.1.6 on 2021-11-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendant', '0005_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
