# Generated by Django 3.1.6 on 2021-11-22 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendant', '0006_student_student_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absent',
            options={'permissions': (('can_view_student', 'can_view_student'),)},
        ),
    ]
