# Generated by Django 3.1.6 on 2021-11-22 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendant', '0007_auto_20211122_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absent',
            options={},
        ),
        migrations.AddField(
            model_name='student',
            name='student_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
