# Generated by Django 3.1.6 on 2021-11-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendant', '0008_auto_20211122_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absent',
            name='absent_type',
            field=models.CharField(blank=True, choices=[('n', 'حضوری'), ('v', 'مجازی'), ('e', 'امتحان'), ('d', 'اخراج از کلاس')], default='N', max_length=1),
        ),
    ]
