# Generated by Django 3.1.6 on 2022-02-09 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=50)),
                ('school_phone', models.CharField(max_length=30)),
                ('school_address', models.CharField(max_length=100)),
                ('studyfield_code_list', models.TextField(blank=True, max_length=120, null=True)),
                ('studyfield_name_list', models.TextField(blank=True, max_length=1024, null=True)),
                ('school_sms_api', models.CharField(blank=True, max_length=120, null=True)),
                ('school_sms_username', models.CharField(blank=True, max_length=30, null=True)),
                ('school_sms_password', models.CharField(blank=True, max_length=30, null=True)),
                ('school_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('student_name', models.CharField(blank=True, max_length=50, null=True)),
                ('studyfield_code', models.CharField(blank=True, max_length=10, null=True)),
                ('studyfield_name', models.CharField(blank=True, max_length=40, null=True)),
                ('input_date', models.DateField(blank=True, null=True)),
                ('parent_mobile', models.CharField(max_length=11)),
                ('student_level', models.CharField(blank=True, choices=[('10', 'دهم'), ('11', 'یازدهم'), ('12', 'دوازدهم')], default='10', max_length=2)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendant.school')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_send', models.DateField(blank=True, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendant.student')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('course_name', models.CharField(blank=True, max_length=50, null=True)),
                ('course_level', models.CharField(blank=True, max_length=2, null=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendant.school')),
            ],
        ),
        migrations.CreateModel(
            name='Absent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absent_date', models.DateField()),
                ('sent', models.BooleanField(default=False)),
                ('absent_type', models.CharField(blank=True, choices=[('n', 'غیبت حضوری'), ('v', 'غیبت مجازی'), ('e', 'غیبت امتحان'), ('d', 'اخراج از کلاس'), ('d', 'تاخیر در کلاس '), ('d', 'فرار از مدرسه'), ('d', 'بی انظباطی')], default='n', max_length=1)),
                ('absent_detail', models.TextField(blank=True, max_length=512, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendant.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendant.student')),
            ],
        ),
    ]
