# Generated by Django 3.1.6 on 2021-12-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendant', '0002_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_phone',
            field=models.CharField(max_length=30),
        ),
    ]
