# Generated by Django 3.1.6 on 2021-12-02 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendant', '0002_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('classroom_field', models.CharField(blank=True, default='ریاضی', max_length=100)),
                ('classroom_name', models.CharField(blank=True, default='', max_length=100)),
                ('classroom_level', models.CharField(blank=True, choices=[('10', 'دهم'), ('11', 'یازدهم'), ('12', 'دوازدهم')], default='10', max_length=2)),
                ('school_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendant.school')),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='student_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendant.classroom'),
        ),
    ]
