# Generated by Django 3.1.6 on 2021-12-26 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendant', '0003_auto_20211226_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='studyfield_code_list',
        ),
    ]
