# Generated by Django 3.1.6 on 2021-12-26 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendant', '0005_school_studyfield_code_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='studyfield_Code',
            new_name='studyfield_code',
        ),
    ]
