# Generated by Django 3.1.6 on 2021-12-02 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendant', '0005_auto_20211202_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='classroom',
            new_name='school',
        ),
    ]
