# Generated by Django 3.1.6 on 2021-12-26 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendant', '0006_auto_20211226_1458'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudyField',
        ),
    ]
