# Generated by Django 3.1.6 on 2021-12-22 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendant', '0008_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
