# Generated by Django 3.1.6 on 2021-12-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendant', '0009_school_studyfield_code_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='studyfield_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
