# Generated by Django 3.1.6 on 2021-12-26 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendant', '0010_student_studyfield_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studyfield_code_list', models.TextField(blank=True, max_length=120, null=True)),
                ('studyfield_name_list', models.TextField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='school',
            name='studyfield_code_list',
        ),
        migrations.AddField(
            model_name='school',
            name='StudyField',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendant.studyfield'),
        ),
    ]
