# Generated by Django 3.1.6 on 2021-12-24 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendant', '0010_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='student',
        ),
    ]
