# Generated by Django 3.1.6 on 2021-12-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendant', '0011_auto_20211224_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='date_send',
            field=models.DateField(blank=True, null=True),
        ),
    ]
