# Generated by Django 3.1.6 on 2021-12-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendant', '0012_auto_20211226_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absent',
            name='absent_type',
            field=models.CharField(blank=True, choices=[('n', 'غیبت حضوری'), ('v', 'غیبت مجازی'), ('e', 'غیبت امتحان'), ('d', 'اخراج از کلاس'), ('d', 'تاخیر در کلاس '), ('d', 'فرار از مدرسه'), ('d', 'بی انظباطی')], default='n', max_length=1),
        ),
    ]
